### ISSUE TITLE
JSON file Creation

### ISSUE THREAD

**Issue by bodhisha** [Open-Sourced-Olaf/Get-svg-icons#1]
Create a JSON file of all the key-value pairs of icon_names & their corresponding svg

**Comment by m2chan** [comment]
Just to clarify the fields we need to scrape. Take this icon as an example: https://icons.getbootstrap.com/icons/app-indicator/

We need:
* name: app_indicator
* tags: app, application, ios, android, notification, square (maybe split into a list)
* icon_font: <i class="bi bi-app-indicator"></i>
* svg: <svg xmlns="http://www.w3.org/2000/svg" .....
