### ISSUE TITLE
Update VS Marketplace documentation

### ISSUE THREAD

**Issue by rashi-s17** [Open-Sourced-Olaf/Get-svg-icons#24]
In the VS Marketplace documentation, the demo gif's do not load. It will be great if that can be fixed.

**Comment by anjalisoni3655** [comment]
We can look into that. Can you assign this to me and @steven-tey

**Comment by rashi-s17** [comment]
Sure, go ahead!

**Comment by rashi-s17** [comment]
Resolved by #26
